### ISSUE TITLE
Question about Refer-kitti-2's label and Kitti's label

### ISSUE THREAD

**Issue by Lwzzzzzz** [zyn213/TempRMOT#12]
Based on my observation, the bbox of a certain target in Refer-kitti does not match the bbox of the same target in KITTI, and there is a single digit error between the two. May I ask if this is due to your correction of the bbox or my misunderstanding of the KITTI dataset?

For example, Video 0 Obj 2 in KITTI:

0 2 Pedestrian 0 0 -2.523309 **1106.137292 166.576807 1204.470628 323.876144** ...

and same obj in Refer-KITTI-2:

0,0,**1105.999755859375,175.9998779296875,92.99971771240234,142.9998779296875**,...

**Comment by zyn213** [comment]
Yes, we have corrected and regenerated labels_with_ids in Refer-KITTI-V2.

**Comment by Lwzzzzzz** [comment]
Thank you for your patient reply.
