### ISSUE TITLE
Issues about inference

### ISSUE THREAD

**Issue by ZHuangyeei** [zyn213/TempRMOT#13]
Why does a particular referring expression yield no inference results on Refer-KITTI-V2? 
![image](https://github.com/user-attachments/assets/ed262759-cc5f-4fbe-bce7-7f8988f23732)

**Comment by zyn213** [comment]
Hi, please verify that the parameters you provided in the [evaluate_rmot.sh](https://github.com/zyn213/TempRMOT/blob/main/TrackEval/scripts/evaluate_rmot.sh) are correct.

**Comment by Jasper0068** [comment]
Why is it that when I use the checkpoint inference put out by the author, the HOTA value is evaluated differently each time? Is there some randomized algorithm in the mix? Take TransRMOT for example

**Comment by LX0912R** [comment]
> Why is it that when I use the checkpoint inference put out by the author, the HOTA value is evaluated differently each time? Is there some randomized algorithm in the mix? Take TransRMOT for example

Hello, I've also encountered a similar issue.
Furthermore, I've observed similar issues in other open-source code built upon TransRMOT.
Have you found the specific reason for this?
Best regards.
