### ISSUE TITLE
Questions about the results of the TransRMOT frame correction mentioned in the paper

### ISSUE THREAD

**Issue by BelieveF** [zyn213/TempRMOT#2]
Hello, thank you for your excellent work. I would like to know how to get the result after correction of TransRMOT? How did TransRMOT achieve a HOTA of 46.56? I would appreciate it if you could let me know the implementation details!
![Uploading image.png…]()

**Comment by zyn213** [comment]
TransRMOT has a small bug when obtaining gt and you only need to change two lines to fix it:
![image](https://github.com/zyn213/TempRMOT/assets/94900013/03fa3440-1e85-4b72-89cd-dc4ccdb40596)
Please refer the [inference.py](https://github.com/zyn213/TempRMOT/blob/main/inference.py#L394) for more details.

**Comment by BelieveF** [comment]
> TransRMOT 在获取 gt 时有一个小错误，你只需要改两行就可以修复了： ![图像](https://private-user-images.githubusercontent.com/94900013/342652759-03fa3440-1e85-4b72-89cd-dc4ccdb40596.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMDYxMjUsIm5iZiI6MTcxOTMwNTgyNSwicGF0aCI6Ii85NDkwMDAxMy8zNDI2NTI3NTktMDNmYTM0NDAtMWU4NS00YjcyLTg5Y2QtZGM0Y2NkYjQwNTk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDA4NTcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmM2ZhNjIxZDkwYjk5NTY5YTNmMTExZjgyNDg3MTVjMDdiOWQzMmU2MWUxZDljOWFiZDBiZjQ2ZDU3MWMyY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hKuvAuMwtXwSvtVUlpw2UKazMi8UKdBrl86Cz9SAGSI) 详情请参考 [inference.py](https://github.com/zyn213/TempRMOT/blob/main/inference.py#L394)。

Thank you very much for your reply. I also think TransRMOT should not have such a low HOTA. I will go and modify it now
