### ISSUE TITLE
Regarding the training time of TempRMOT

### ISSUE THREAD

**Issue by BelieveF** [zyn213/TempRMOT#3]
Hello, I am planning to reproduce your excellent work, and I would like to know in advance the training time of TempRMOT and the approximate training time of one epoch. If you could tell me, I would be very grateful.

**Comment by zyn213** [comment]
Hi, thanks for your interest! 
If you train on 4 RTX 4090 GPUs for 60 epochs, the training time of one epoch is about 29 minutes and the  total training time is about 1 day and 7 hours. 
However, experiments show that the model has converged after 50 epochs, so it is also possible to train only **50 epochs**, which can save more time.

**Comment by BelieveF** [comment]
> Hi, thanks for your interest! If you train on 4 RTX 4090 GPUs for 60 epochs, the training time of one epoch is about 29 minutes and the total training time is about 1 day and 7 hours. However, experiments show that the model has converged after 50 epochs, so it is also possible to train only **50 epochs**, which can save more time.

hi,Thank you for your answer, I have understood the training time now, wish you a smooth work ~. ：）
