### ISSUE TITLE
Issue about the result of Refer-KITTI

### ISSUE THREAD

**Issue by Zhaozeyong** [zyn213/TempRMOT#4]
Hi, I really admire your outstanding work and am very interested in it. However, I have a question about the weights and commands you provided for verifying Refer-KITTI. The results I obtained were 50.246 (HOTA), 38.839 (DetA), 65.182 (AssA), 50.777 (DetRe), 60.68 (DetPr), 69.588 (AssRe), 88.718 (AssPr), and 90.466 (LOCA). It seems that the HOTA dropped by 2% compared to your published result.

Thank you for your help!

**Comment by zyn213** [comment]
Sorry for the mistake. It seems to be because I reorganized the code. We will update this soon.

**Comment by Project627** [comment]
Hi, Happy National Day. I would like to ask if you have corrected this problem?
