### ISSUE TITLE
Questions about frame correction, how to do this operation?

### ISSUE THREAD

**Issue by ydhcg-BoBo** [zyn213/TempRMOT#5]

**Comment by zyn213** [comment]
Hi, thanks for your interest. Please refer to issue [#2](https://github.com/zyn213/TempRMOT/issues/2) for the frame correction.

**Comment by ydhcg-BoBo** [comment]
Thank you. Moreover, When I was testing I encountered the following problem:
trackeval.utils.TrackEvalException: Tracker predicts the same ID more than once in a single timestep (seq: 0005+black-cars-in-the-left, frame: 11, ids: 4 5)
How can I solve it, thank you.

**Comment by zyn213** [comment]
Close due to inactivity.
