### ISSUE TITLE
How to calculate HOTA on test set?

### ISSUE THREAD

**Issue by WJ-Huang** [zyn213/TempRMOT#7]
Hello the authors, your work is amazing and interesting. When following your code, I cannot find a place to calculate the metrics, could you give some hints? I appreciate your help! @zyn213

**Comment by zyn213** [comment]
Hi, you can get the main results by runing
```
cd TrackEval/script
sh evaluate_rmot.sh
```

**Comment by zyn213** [comment]
Close due to inactivity.
