### ISSUE TITLE
Any plan to open source the checkpoint on Refer-KITTI 2?

### ISSUE THREAD

**Issue by WJ-Huang** [zyn213/TempRMOT#8]
Dear author,

Thank you for sharing your amazing work! I am trying to run the model but notice that the link for the checkpoint on refer-KITTI 2 is deprecated. Do you have any plans to open-source it in the near future?

Best,

**Comment by zyn213** [comment]
Hi, is your problem solved? I don't know why can't download it directly from the readme. But, you can download through: https://github.com/zyn213/TempRMOT/releases/tag/v1.0

**Comment by WJ-Huang** [comment]
Thank you so much! It solves my problem!
